<?php

namespace Stojg\Puny;

/**
 * Test class for BlogFile.
 * Generated by PHPUnit on 2012-06-11 at 16:29:10.
 */
class BlogFileTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var BlogFile
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new BlogFile('tests/src/Stojg/Puny/fixtures');
	}

	/**
	 * @covers Stojg\Puny\BlogFile::getPosts
	 */
	public function testGetPosts() {
		$this->assertEquals(6, count($this->object->getPosts()));
		$this->assertEquals(6, count($this->object->getPosts(10)));
		$this->assertEquals(5, count($this->object->getPosts(5)));
	}

	/**
	 *
	 */
	public function testtestGetPostsIsSorted() {
		$posts = $this->object->getPosts();

		while(count($posts)>2) {
			$first = array_shift($posts);
			$last = array_pop($posts);
			$this->assertGreaterThan($last->getDate('U'),$first->getDate('U'));
		}
		

	}


	/**
	 * @covers Stojg\Puny\BlogFile::getPost
	 */
	public function testGetPost() {
		$post = $this->object->getPost('2012-06-09-movie-night');
		$this->assertTrue($post instanceof Post);
		$this->assertEquals('movie night', $post->getTitle());
	}

}