<?php

namespace stojg\puny;

/**
 * Test class for PageList
 * Generated by PHPUnit on 2012-06-11 at 16:29:10.
 */
class FileSourceTest extends \PHPUnit_Framework_TestCase {

	protected $obj = null;

	public function setUp() {
		$this->obj = new FileSource('tests/src/stojg/puny/models/fixtures/');
	}

	public function testInstance() {
		$this->assertTrue($this->obj instanceof DataSource);
	}

	public function testCount() {
		$this->assertEquals(7, $this->obj->count());
	}

	public function testLimit() {
		$this->obj->limit(5);
		$this->assertEquals(5, $this->obj->count());
	}

	public function testOffset() {
		$this->obj->offset(4);
		$this->assertEquals(3, $this->obj->count());
	}

	public function testLimitAndOffset() {
		$this->obj->offset(2)->limit(1);
		$this->assertEquals(1, $this->obj->count());
	}

	public function testFirst() {
		$json = $this->obj->first();
		$post = json_decode($json);
		$this->assertEquals($post->title, 'draft-post');	
	}
}