<?php

namespace stojg\puny;

/**
 * Test class for PageList
 * Generated by PHPUnit on 2012-06-11 at 16:29:10.
 */
class PageListTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var PageList
	 */
	protected $object;

	protected function setUp() {
		$this->object = new PageList(new FileSource('tests/src/stojg/puny/models/fixtures/'));
	}

	public function testInstance() {
		$this->assertTrue($this->object instanceof PageList);
	}

	public function testGetSource() {
		$this->assertTrue($this->object->getSource() instanceof DataSource);
	}

	public function testCount() {
		$this->assertEquals(7, $this->object->count());
	}

	public function testLimit() {
		$this->object->limit(5);
		$this->assertEquals(5, $this->object->count());
	}

	public function testLimitAndOffset() {
		$this->object->limit(5)->offset(6);
		$this->assertEquals(1, $this->object->count());
	}

	public function testFirst() {
		$page = $this->object->first();
		$this->assertTrue($page instanceof Page);
		$this->assertEquals('draft-post', $page->title());
		$this->assertEquals('2012-07-09 10:36', $page->date());
		$this->assertEquals('true', $page->draft());
		$this->assertEquals('true', $page->comments());
		$this->assertEquals(1054, strlen($page->content()));
	}

	public function testGetPage(){
		$pages = $this->object->itemsPerPage(2)->page(1);
		
		$this->assertEquals(2, count($pages));
		$this->assertEquals('The three musketeers', $pages[0]->title());
		$this->assertEquals('How to setup up Octopress', $pages[1]->title());
		
		$pages = $this->object->itemsPerPage(3)->page(2);
		$this->assertEquals(3, count($pages));
		$this->assertEquals('movie night', $pages[0]->title());
		$this->assertEquals('Quiz results', $pages[1]->title());
		$this->assertEquals('Quiz night', $pages[2]->title());
	}

	public function testGet() {
		$pages = $this->object->get();
		$this->assertEquals(6, count($pages));
		$this->assertEquals('movie night', $pages[0]->title());
		$this->assertEquals('How to setup up Octopress', $pages[6]->title());
	}

	public function testGetDraft() {
		$pages = $this->object->get(true);
		$this->assertEquals(7, count($pages));
		$this->assertEquals('draft-post', $pages[0]->title());
		$this->assertEquals('How to setup up Octopress', $pages[6]->title());
	}

}