<?php

namespace stojg\puny\models;

/**
 * Test class for User.
 * Generated by PHPUnit on 2012-06-17 at 15:19:56.
 */
class UserTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var User
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new User;
	}

	/**
	 * @covers stojg\puny\models\User::getUsername
	 */
	public function testGetUsername() {
		// Remove the following lines when you implement this test.
		$this->assertEquals(null, $this->object->getUsername());
	}

	/**
	 * @covers stojg\puny\models\User::setUsername
	 */
	public function testSetUsername() {
		$this->object->setUsername('klaus');
		$this->assertEquals('klaus', $this->object->getUsername());
	}

	/**
	 * @covers stojg\puny\models\User::getPassword
	 */
	public function testGetPassword() {
		$this->assertEquals(null, $this->object->getPassword());
	}

	/**
	 * @covers stojg\puny\models\User::setPassword
	 */
	public function testSetPassword() {
		$this->object->setPassword('poop');
		$this->assertEquals('poop', $this->object->getPassword());
	}

	/**
	 * @covers stojg\puny\models\User::login
	 * @todo Implement testLogin().
	 */
	public function testLogin() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers stojg\puny\models\User::logout
	 * @todo Implement testLogout().
	 */
	public function testLogout() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers stojg\puny\models\User::valid
	 * @todo Implement testValid().
	 */
	public function testValid() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}
}